---

- name: Install dependencies with pip
  pip: name={{item}}
  with_items:
    - docopt

- name: Install dependencies with apt.
  apt: pkg=python-pygments state=present

- name: Clone cheat repo
  git: repo=https://github.com/chrisallenlane/cheat.git dest=~/opt/cheat

- name: Run setup
  shell: chdir=~/opt/cheat python setup.py install
  sudo: yes
